version: '3'
    
services:
  web:
    build: .
    # Give time for statetrace to create replication slot before running migrations
    command: bash -c "sleep 10s && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - statetrace

  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
      - "-c"
      - "max_wal_senders=1"
      - "-c"
      - "max_replication_slots=2"
  
  statetrace:
    image: statetraceofficial/statetrace-beta
    environment:
      - DATABASE_URL=postgres://postgres:postgres@statetrace_db:5433/postgres
      - SECRET_KEY_BASE=123456789123456789123456789123456789123456789123456789123456789123456789
      - STATETRACE_DEMO_MODE=1
      - PORT=9999
    depends_on:
      - statetrace_db
      - db
    ports:
      - "9999:9999"

  statetrace_db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    command:
      - "postgres"
      - "-p"
      - "5433"
  