# Generated by Django 2.2.15 on 2020-08-18 05:00

from django.db import migrations
from django.conf import settings
from django.contrib.auth.hashers import make_password


def forwards_func(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.create(username='root', is_staff=True, is_superuser=True, first_name="Admin", last_name="User", password=make_password('password'))
    User.objects.create(username='mary', is_staff=True, first_name="Mary", last_name="Stuart", password=make_password('password'))
    User.objects.create(username='bob', first_name="Bob", last_name="Barker", password=make_password('password'))


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func)
    ]
