# Generated by Django 2.2.15 on 2020-08-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='new_field',
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
